package app.ds3wiki

const val NOTIFICATION_REQUEST_CODE = 0x0100
const val NOTIFICATION_UNIQUE_ID = 0x1000

const val NOTIFICATION_ID = "NOTIFICATION_ID"
const val NOTIFICATION_NAME = "NOTIFICATION_NAME"